# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  name: ACE

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\git_test'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)'
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CmdLine@2
  inputs:
    script: 'cd C:\Program Files\IBM\ACE\12.0.9.0\server\bin&&mqsiprofile&&mqsicreatebar -data "C:\Users\anupa\IBM\ACET12\workspace" -b "C:\Program Files\IBM\ACE\12.0.9.0\%APP_NAME%\target\ace\%APP_NAME%.bar" -cleanBuild  -a %APP_NAME% -deployAsSource -trace -v createbartrace.txt&&mqsideploy TESTNODE -e default -a "C:\Program Files\IBM\ACE\12.0.9.0\%APP_NAME%\target\ace\%APP_NAME%.bar"'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
